"""document aligned initial schema

Revision ID: 20260720_0001
Revises:
Create Date: 2026-07-20 10:40:55.392517
"""

# ruff: noqa: E501, I001

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '20260720_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_versions',
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('model', 'prompt', 'retrieval', 'standard')", name='ck_config_kind'),
    sa.PrimaryKeyConstraint('configuration_id'),
    sa.UniqueConstraint('kind', 'version', name='uq_config_version')
    )
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_versions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_versions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_versions_version'), ['version'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('paper_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_is_internal'), ['is_internal'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_user_last_message', ['user_id', 'last_message_at'], unique=False)
        batch_op.create_index('ix_sessions_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('configuration_revisions',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configuration_versions.configuration_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('revision_id'),
    sa.UniqueConstraint('configuration_id', 'version', name='uq_config_revision_version')
    )
    with op.batch_alter_table('configuration_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_revisions_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_revisions_kind'), ['kind'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('status_code >= 100 AND status_code <= 599', name='ck_idempotency_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('user_id', 'key', 'method', 'path', name='uq_idempotency')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_user_id'), ['user_id'], unique=False)

    op.create_table('papers',
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parse_progress', sa.Float(), nullable=False),
    sa.Column('index_status', sa.String(length=32), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=True),
    sa.Column('failure', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('active_index_version', sa.Integer(), nullable=True),
    sa.Column('ingestion_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'mineru_parsing', 'ocr_processing', 'cleaning', 'quality_check', 'indexing', 'ready', 'failed', 'deleting', 'deleted')", name='ck_papers_status'),
    sa.CheckConstraint('parse_progress >= 0 AND parse_progress <= 1', name='ck_papers_parse_progress'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index('ix_papers_owner_content_hash', ['owner_id', 'content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_papers_owner_paper', ['owner_id', 'paper_id'], unique=False)
        batch_op.create_index('ix_papers_owner_updated', ['owner_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_paper_version_id'), ['paper_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_papers_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('error_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_tasks_status'),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name='ck_tasks_progress'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tasks_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index('ix_tasks_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('route_type', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('retrieval_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('answer_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user')", name='ck_chat_messages_role'),
    sa.CheckConstraint("route_type IS NULL OR route_type IN ('fact', 'explain', 'review', 'score', 'follow_up', 'out_of_scope')", name='ck_chat_messages_route'),
    sa.CheckConstraint("status IS NULL OR status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled', 'partial')", name='ck_chat_messages_status'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_chat_messages_confidence'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_messages_session_created', ['session_id', 'created_at'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_tasks_message',
            'chat_messages',
            ['message_id'],
            ['message_id'],
            ondelete='SET NULL',
        )

    op.create_table('paper_versions',
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=128), nullable=False),
    sa.Column('cleaning_version', sa.String(length=128), nullable=False),
    sa.Column('chunk_schema_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'superseded', 'failed')", name='ck_paper_versions_status'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_version_id'),
    sa.UniqueConstraint('paper_id', 'version_number', name='uq_paper_version_number')
    )
    with op.batch_alter_table('paper_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_versions_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_versions_paper_id'), ['paper_id'], unique=False)

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_papers_current_version',
            'paper_versions',
            ['paper_version_id'],
            ['paper_version_id'],
        )

    op.create_table('reading_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('paper_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('template_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('claims_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_reading_reports_status'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('reading_reports', schema=None) as batch_op:
        batch_op.create_index('ix_reading_reports_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_reports_user_id'), ['user_id'], unique=False)

    op.create_table('session_papers',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_session_papers_position'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'paper_id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_paper_position')
    )
    with op.batch_alter_table('session_papers', schema=None) as batch_op:
        batch_op.create_index('ix_session_papers_paper', ['paper_id', 'session_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_workflow_runs_status'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workflow_run_id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_runs_user_id'), ['user_id'], unique=False)

    op.create_table('citations',
    sa.Column('citation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('evidence_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('paper', 'standard')", name='ck_citations_source_type'),
    sa.CheckConstraint('similarity >= 0', name='ck_citations_similarity'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id'),
    sa.UniqueConstraint('message_id', 'evidence_id', name='uq_citation_message_evidence')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citations_paper_id'), ['paper_id'], unique=False)

    op.create_table('ingestion_quality_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('indexable_chunk_count', sa.Integer(), nullable=False),
    sa.Column('blocking_error_count', sa.Integer(), nullable=False),
    sa.Column('expected_mapping_count', sa.Integer(), nullable=False),
    sa.Column('mapped_chunk_count', sa.Integer(), nullable=False),
    sa.Column('mapping_failure_count', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ready', 'failed')", name='ck_quality_reports_status'),
    sa.CheckConstraint('indexable_chunk_count >= 0 AND blocking_error_count >= 0 AND expected_mapping_count >= 0 AND mapped_chunk_count >= 0 AND mapping_failure_count >= 0', name='ck_quality_reports_counts'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('ingestion_quality_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_quality_reports_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_quality_reports_paper_version_id'), ['paper_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_quality_reports_task_id'), ['task_id'], unique=True)

    op.create_table('media_objects',
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bbox_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_ref', sa.String(length=1024), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('ocr_status', sa.String(length=32), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=128), nullable=True),
    sa.Column('engines_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('raw_response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('failure_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("ocr_status IN ('pending', 'processing', 'success', 'partial', 'failed', 'skipped')", name='ck_media_objects_ocr_status'),
    sa.CheckConstraint('page_number >= 1', name='ck_media_objects_page'),
    sa.CheckConstraint('retry_count >= 0', name='ck_media_objects_retry_count'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id'),
    sa.UniqueConstraint('paper_version_id', 'object_id', name='uq_media_object_version')
    )
    with op.batch_alter_table('media_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_objects_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_objects_paper_version_id'), ['paper_version_id'], unique=False)

    op.create_table('message_feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("feedback_type IN ('like', 'dislike', 'issue')", name='ck_feedback_type'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    with op.batch_alter_table('message_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_feedback_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('paper_chunks',
    sa.Column('paper_chunk_id', sa.String(length=36), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=128), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_role', sa.String(length=64), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=False),
    sa.Column('section_path_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=1024), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=True),
    sa.Column('parent_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('prev_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('next_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('retrieval_weight', sa.Float(), nullable=False),
    sa.Column('quality_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('parser_version', sa.String(length=128), nullable=False),
    sa.Column('cleaning_version', sa.String(length=128), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('page_start >= 1 AND page_end >= page_start', name='ck_chunks_pages'),
    sa.CheckConstraint('retrieval_weight >= 0', name='ck_chunks_retrieval_weight'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_chunk_id'),
    sa.UniqueConstraint('paper_version_id', 'source_chunk_id', name='uq_paper_chunk_version_source')
    )
    with op.batch_alter_table('paper_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunks_paper_version_page', ['paper_version_id', 'page_start'], unique=False)
        batch_op.create_index('ix_chunks_role_indexable', ['content_role', 'indexable'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_chunks_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_chunks_indexable'), ['indexable'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_chunks_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_chunks_paper_version_id'), ['paper_version_id'], unique=False)

    op.create_table('paper_ingestion_runs',
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parser_version', sa.String(length=128), nullable=False),
    sa.Column('cleaning_version', sa.String(length=128), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_ingestion_runs_status'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('ingestion_run_id')
    )
    with op.batch_alter_table('paper_ingestion_runs', schema=None) as batch_op:
        batch_op.create_index('ix_ingestion_version_config', ['paper_version_id', 'parser_version', 'cleaning_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_ingestion_runs_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_ingestion_runs_paper_version_id'), ['paper_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_ingestion_runs_task_id'), ['task_id'], unique=True)

    op.create_table('parsed_blocks',
    sa.Column('parsed_block_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('paper_version_id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bbox_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_ref', sa.String(length=1024), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('page_number >= 1', name='ck_parsed_blocks_page'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parsed_block_id'),
    sa.UniqueConstraint('paper_version_id', 'block_id', name='uq_parsed_block_version')
    )
    with op.batch_alter_table('parsed_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_blocks_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_blocks_paper_version_id'), ['paper_version_id'], unique=False)

    op.create_table('qa_evaluations',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('reference_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('verdict', sa.String(length=64), nullable=True),
    sa.Column('retrieval_result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('validator_result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    with op.batch_alter_table('qa_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_evaluations_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_evaluations_task_id'), ['task_id'], unique=True)

    op.create_table('rag_mappings',
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('paper_version_id', sa.String(length=36), nullable=True),
    sa.Column('source_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('ragflow_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed', 'deleted')", name='ck_rag_mappings_status'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['paper_version_id'], ['paper_versions.paper_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mapping_id'),
    sa.UniqueConstraint('paper_version_id', 'source_chunk_id', 'content_sha256', name='uq_rag_chunk_map')
    )
    with op.batch_alter_table('rag_mappings', schema=None) as batch_op:
        batch_op.create_index('ix_rag_document_chunk', ['dataset_id', 'document_id', 'ragflow_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_mappings_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_mappings_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_mappings_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_mappings_paper_version_id'), ['paper_version_id'], unique=False)

    op.create_table('reading_report_papers',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_report_papers_position'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reading_reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'paper_id'),
    sa.UniqueConstraint('report_id', 'position', name='uq_report_paper_position')
    )
    op.create_table('report_exports',
    sa.Column('export_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('markdown', 'pdf', 'docx')", name='ck_report_exports_format'),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_report_exports_status'),
    sa.ForeignKeyConstraint(['report_id'], ['reading_reports.report_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('export_id')
    )
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_exports_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_exports_task_id'), ['task_id'], unique=True)

    op.create_table('review_results',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer', sa.String(length=32), nullable=False),
    sa.Column('dimension', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('final_judgement', sa.Text(), nullable=True),
    sa.Column('opinion_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("position IS NULL OR position IN ('critical', 'supportive', 'mixed')", name='ck_review_position'),
    sa.CheckConstraint("reviewer IN ('review_a', 'review_b')", name='ck_review_reviewer'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_review_confidence'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('message_id', 'reviewer', name='uq_review_message_reviewer')
    )
    with op.batch_alter_table('review_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_results_message_id'), ['message_id'], unique=False)

    op.create_table('trace_records',
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('node_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=True),
    sa.Column('output_digest', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('metrics_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'retried', 'failed', 'skipped')", name='ck_trace_records_status'),
    sa.CheckConstraint('duration_ms >= 0', name='ck_trace_duration'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('trace_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_records_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_records_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trace_records_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_traces_request_created', ['request_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_papers_current_version', type_='foreignkey')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_message', type_='foreignkey')

    with op.batch_alter_table('trace_records', schema=None) as batch_op:
        batch_op.drop_index('ix_traces_request_created')
        batch_op.drop_index(batch_op.f('ix_trace_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_trace_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_trace_records_message_id'))
        batch_op.drop_index(batch_op.f('ix_trace_records_correlation_id'))

    op.drop_table('trace_records')
    with op.batch_alter_table('review_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_results_message_id'))

    op.drop_table('review_results')
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_exports_task_id'))
        batch_op.drop_index(batch_op.f('ix_report_exports_report_id'))

    op.drop_table('report_exports')
    op.drop_table('reading_report_papers')
    with op.batch_alter_table('rag_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_mappings_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_rag_mappings_paper_id'))
        batch_op.drop_index(batch_op.f('ix_rag_mappings_document_id'))
        batch_op.drop_index(batch_op.f('ix_rag_mappings_dataset_id'))
        batch_op.drop_index('ix_rag_document_chunk')

    op.drop_table('rag_mappings')
    with op.batch_alter_table('qa_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_evaluations_task_id'))
        batch_op.drop_index(batch_op.f('ix_qa_evaluations_message_id'))

    op.drop_table('qa_evaluations')
    with op.batch_alter_table('parsed_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_blocks_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_parsed_blocks_paper_id'))

    op.drop_table('parsed_blocks')
    with op.batch_alter_table('paper_ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_ingestion_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_paper_ingestion_runs_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_paper_ingestion_runs_paper_id'))
        batch_op.drop_index('ix_ingestion_version_config')

    op.drop_table('paper_ingestion_runs')
    with op.batch_alter_table('paper_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_chunks_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_paper_chunks_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_chunks_indexable'))
        batch_op.drop_index(batch_op.f('ix_paper_chunks_content_sha256'))
        batch_op.drop_index('ix_chunks_role_indexable')
        batch_op.drop_index('ix_chunks_paper_version_page')

    op.drop_table('paper_chunks')
    with op.batch_alter_table('message_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_feedback_message_id'))

    op.drop_table('message_feedback')
    with op.batch_alter_table('media_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_objects_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_media_objects_paper_id'))

    op.drop_table('media_objects')
    with op.batch_alter_table('ingestion_quality_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_quality_reports_task_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_quality_reports_paper_version_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_quality_reports_paper_id'))

    op.drop_table('ingestion_quality_reports')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_paper_id'))
        batch_op.drop_index(batch_op.f('ix_citations_message_id'))
        batch_op.drop_index(batch_op.f('ix_citations_document_id'))
        batch_op.drop_index(batch_op.f('ix_citations_chunk_id'))

    op.drop_table('citations')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_session_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('session_papers', schema=None) as batch_op:
        batch_op.drop_index('ix_session_papers_paper')

    op.drop_table('session_papers')
    with op.batch_alter_table('reading_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_reports_user_id'))
        batch_op.drop_index('ix_reading_reports_user_created')

    op.drop_table('reading_reports')
    with op.batch_alter_table('paper_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_versions_paper_id'))
        batch_op.drop_index(batch_op.f('ix_paper_versions_content_sha256'))

    op.drop_table('paper_versions')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_session_created')
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_task_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index('ix_tasks_user_created')
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_request_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_message_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_correlation_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_status'))
        batch_op.drop_index(batch_op.f('ix_papers_paper_version_id'))
        batch_op.drop_index('ix_papers_owner_updated')
        batch_op.drop_index('ix_papers_owner_paper')
        batch_op.drop_index(batch_op.f('ix_papers_owner_id'))
        batch_op.drop_index('ix_papers_owner_content_hash')

    op.drop_table('papers')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_user_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('configuration_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_revisions_kind'))
        batch_op.drop_index(batch_op.f('ix_configuration_revisions_configuration_id'))

    op.drop_table('configuration_revisions')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_updated')
        batch_op.drop_index('ix_sessions_user_last_message')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_is_internal'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('configuration_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_versions_version'))
        batch_op.drop_index(batch_op.f('ix_configuration_versions_kind'))
        batch_op.drop_index(batch_op.f('ix_configuration_versions_active'))

    op.drop_table('configuration_versions')
    # ### end Alembic commands ###
